import Foundation

/// A selectable citation system with baked-in guidance that's woven into the
/// assistant's instructions so it cites authorities the way the user expects.
/// Covers the general systems (Bluebook, Indigo Book, MLA) plus each state's
/// citation norms, drawn from *Introduction to Basic Legal Citation* (Peter W.
/// Martin, Cornell LII), §§ 2-230 / 7-500, and Bluebook Table T1. State guidance
/// is paraphrased from the guide's § 7-500 table (with court-rule citations).
public struct CitationStyle: Identifiable, Hashable, Sendable {
    public let id: String
    public let displayName: String
    public let guidance: String

    public init(id: String, displayName: String, guidance: String) {
        self.id = id
        self.displayName = displayName
        self.guidance = guidance
    }
}

public enum CitationStyleCatalog {
    public static let bluebook = CitationStyle(
        id: "bluebook",
        displayName: "The Bluebook",
        guidance: "Follow The Bluebook: A Uniform System of Citation — the dominant U.S. legal citation system. Use Table T1 for jurisdiction-specific reporters and abbreviations, pin-cite to the exact page, and use short forms (id., supra) after the first full reference."
    )

    public static let indigoBook = CitationStyle(
        id: "indigo-book",
        displayName: "The Indigo Book",
        guidance: "Follow The Indigo Book — a free, public-domain implementation of the Bluebook's citation rules (law.resource.org/pub/us/code/blue/IndigoBook.html). Its case, statute, and secondary-source forms track the Bluebook, so cite as you would under Bluebook rules."
    )

    public static let mla = CitationStyle(
        id: "mla",
        displayName: "MLA",
        guidance: "Follow MLA style (Modern Language Association): author–page parenthetical references in text with a Works Cited list. Suited to academic/non-litigation writing rather than court filings; legal authorities still need enough detail (reporter, court, year) to be located."
    )

    public static let general: [CitationStyle] = [bluebook, indigoBook, mla]

    /// One entry per state, with practical guidance grounded in the guide's
    /// § 7-500 table: controlling reporter(s) and required parallels, any
    /// medium-neutral (public-domain) citation the state adopted, the state's
    /// explicit brief-citation rule, and pinpoint conventions.
    public static let states: [CitationStyle] = [
        state("Alabama", "al", "Alabama requires briefs to comply with either The Bluebook or the ALWD Citation Manual (Ala. R. App. P. 8). When citing authority, cite the specific page numbers where the proposition appears. No-opinion affirmances are not precedent and may not be cited except to establish law of the case, res judicata, collateral estoppel, or procedural bar (Ala. R. App. P. 53). The table of authorities must be alphabetically arranged with cases, statutes, and other authorities listed separately."),
        state("Alaska", "ak", "Alaska permits citation of unpublished decisions for establishing res judicata, estoppel, or law of the case; for other purposes they are not encouraged (Alaska R. App. P. 214). When citing unpublished decisions from a public database, the citation must indicate it is unpublished and specify the database location; for unreported cases not in public databases, a copy must be filed with the brief. Otherwise follow standard reporter format (P.3d) with page pinpoints."),
        state("Arizona", "az", "Arizona uses a public-domain citation system where opinions are cited by year, court designator, and sequential number (e.g., 2005 Ariz. 5) with paragraph numbers for pinpoints (Ariz. Sup. Ct. R. 111), alongside the Pacific Reporter. Memorandum decisions are not precedential and may be cited only for claim or issue preclusion, law of the case, or (if issued after Jan. 1, 2015) limited persuasive value; a hyperlink or copy must be provided."),
        state("Arkansas", "ar", "Arkansas uses an official medium-neutral citation for all post-July 1, 2009 decisions: case name, year, court abbreviation (Ark. for the Supreme Court, Ark. App. for the Court of Appeals), and sequential decision number (Ark. Sup. Ct. & Ct. App. R. 5-2). Parallel citations to the South Western Reporter are required and pinpoints strongly encouraged; all Arkansas Supreme Court and Court of Appeals citations must be to the official reports (R. 4-2)."),
        state("California", "ca", "California allows citations in either the California Style Manual or The Bluebook, applied consistently throughout the document (Cal. R. Ct. 1.200). Case citations must include the official report volume and page with year; no other form is required (Cal. R. Ct. 3.1113). Unpublished opinions generally cannot be cited or relied upon except for law of the case, res judicata, or collateral estoppel (Cal. R. Ct. 8.1115)."),
        state("Colorado", "co", "Colorado uses a public-domain citation format (C.J. Directive 12-01) — year, court abbreviation (CO for the Supreme Court, COA for the Court of Appeals), and sequential number (e.g., 2012 CO 1), with paragraph numbers preceded by ¶ for pinpoints. Parallel citation to the Pacific Reporter is permitted but not required. The format has been mandatory since January 1, 2012 for all published opinions."),
        state("Connecticut", "ct", "Connecticut briefs must cite Connecticut cases to the official reporter only; out-of-state cases may use the official or regional reporter (Conn. R. App. P. § 67-11). For cases available only in electronic databases (Westlaw, LEXIS), the citation must include the case name, docket number, database name and identifiers, court, and full date, with screen/paragraph numbers preceded by an asterisk. Arrange cases alphabetically in the table of authorities."),
        state("Delaware", "de", "Delaware requires Bluebook form with no reference to the State Reporter System or parallel citations (Del. Sup. Ct. R. 14) — e.g., Melson v. Allman, 244 A.2d 85 (Del. 1968). For unreported opinions, cite via LEXIS, Westlaw, or the Delaware form specifying case name, number, date, and judge (e.g., Fox v. Fox, 1998 Del. LEXIS 179 (Del. 1998)). Other authorities follow Bluebook standards."),
        state("Florida", "fl", "Florida prescribes a uniform citation system (Fla. R. App. P. 9.800): Supreme Court cases to the Southern Reporter (So. 3d), district courts of appeal by district (e.g., Fla. 2d DCA), and circuit courts by supplement. For recent unpublished opinions, cite Florida Law Weekly or the slip opinion with the case number. The table of authorities must alphabetically list cases, statutes, and other authorities with page references."),
        state("Georgia", "ga", "Georgia requires full citations to the official Georgia Reports / Georgia Appeals Reports with case name, volume, and page (Ga. Sup. Ct. R. 22), plus the South Eastern Reporter parallel. Cases not yet reported are cited by Supreme Court or Court of Appeals case number and decision date. All citations of authority must be full and complete with pinpoint references."),
        state("Hawaii", "hi", "Cite Hawai\u{2018}i Supreme Court cases to both the official Hawai\u{2018}i Reports and the Pacific Reporter (e.g., 134 Haw. 1, 332 P.3d 144). Unpublished dispositions filed on or after July 1, 2008 may be cited for persuasive value with a copy attached to the brief. Per Haw. R. App. P. 28, include a table of authorities and use electronic citations (identifying the database, court, and date) when a case is available only in a database."),
        state("Idaho", "id", "Cite Idaho cases to the Idaho Reports and the Pacific Reporter, without a required parallel (e.g., 143 Idaho 862, 154 P.3d 433). Per Idaho S. Ct. Internal R. 15(e), citations must conform to The Bluebook or the ALWD Citation Manual. Unpublished opinions may not be cited as authority or precedent in any court; only published opinions carry precedential weight."),
        state("Illinois", "il", "For cases filed on or after July 1, 2011, cite the public-domain designation with paragraph numbers (e.g., 2023 IL 127854, ¶ 35), optionally with the North Eastern Reporter or Illinois Decisions parallel (Ill. Sup. Ct. R. 6). Cases filed before that date cite the official Illinois Reports (or both it and the regional reporter). Nonprecedential orders issued on or after Jan. 1, 2021 may be cited for persuasive value but must be marked non-binding."),
        state("Indiana", "in", "Cite published Indiana opinions to the regional reporter (typically the North Eastern Reporter) with court and year, without a required parallel official citation (e.g., 934 N.E.2d 1120 (Ind. 2010)). Per Ind. R. App. P. 22, memorandum decisions issued after Jan. 1, 2023 require the appellate case number, court, and date in (mem.) format. Pinpoint to the specific pages where the proposition appears."),
        state("Iowa", "ia", "Cite Iowa cases to the North Western Reporter when available; if not reported there, cite the Iowa Reports (e.g., 644 N.W.2d 18 (Iowa 2002)) and include the court and year (Iowa R. App. P. 6.904). Unpublished opinions may be cited in briefs if readily accessible electronically (with an electronic citation indicating where they may be accessed), but they are not controlling authority."),
        state("Kansas", "ks", "Cite Kansas cases to the official Kansas Reports followed by the regional reporter (e.g., 271 Kan. 206, 21 P.3d 542 (2001)) per Kan. Ct. R. 6.08 — the official citation followed by a generally recognized reporter. Memorandum opinions are unpublished and carry no precedential value unless required by K.S.A. 60-2106, though they may be cited for persuasive value on points not addressed by published authority."),
        state("Kentucky", "ky", "Cite Kentucky cases to the South Western Reporter (e.g., S.W.3d (Ky.) for the Supreme Court, (Ky. App.) for the Court of Appeals). Per Ky. R. App. P. 41, opinions designated \u{2018}Not To Be Published\u{2019} are disfavored but may be cited if rendered after Jan. 1, 2003, no published opinion adequately addresses the point, and the opinion is clearly noted as non-binding with its case number, date, and style (e.g., 2019-SC-1234 (Ky. Feb. 20, 2020))."),
        state("Louisiana", "la", "For post-1993 decisions use the public-domain citation with a Southern Reporter parallel (e.g., 2024-01005 (La. 8/20/24), 390 So. 3d 1282); pinpoint with \u{2018}p.\u{2019} after the docket number (e.g., 93-2345, p. 7 (La. 7/15/94)). Per La. Sup. Ct. Gen. Admin. R. § 8 and La. Code Civ. Proc. art. 2168, unpublished opinions posted on court websites may be cited by case name and the court-assigned docket number."),
        state("Maine", "me", "Opinions issued on or after Jan. 1, 1997 use a public-domain citation — calendar year and sequential opinion number (e.g., 2025 ME 64, 340 A.3d 99) — with paragraph-number pinpoints (¶ 14); the Atlantic Reporter is the parallel. Per Me. R. App. P. 12, memorandum decisions and summary orders are not precedent and cannot be cited. See Uniform Maine Citations for citing Maine authorities."),
        state("Maryland", "md", "Cite reported Maryland cases to the official Maryland Reports (e.g., 370 Md. 115, 803 A.2d 527 (2002)) with the Atlantic Reporter parallel. Per Md. Rule 8-504, the brief's table of citations lists cases alphabetically and must reference the official Report. Per Md. Rule 1-104, unreported opinions issued on or after July 1, 2023 may be cited for persuasive value only when no reported authority addresses the issue, identified as unreported with case number, term, and filing date."),
        state("Massachusetts", "ma", "Cite Massachusetts cases to the official Massachusetts Reports (Mass.) / Appeals Court Reports (Mass. App. Ct.) with page pinpoints and year, plus the North Eastern Reporter parallel (Mass. R. App. P. 16(g)). Cite statutes to the official General Laws (G.L. c. __, § __) rather than commercial compilations as the primary source."),
        state("Michigan", "mi", "Michigan uses a distinctive style (Michigan Appellate Opinion Manual): semicolons separate parallel citations and abbreviations omit periods (e.g., 460 Mich 396; 596 NW2d 164 (1999)). Practitioners are encouraged (not strictly required) to follow the manual; in-state briefs should include the Michigan Reports / Michigan Appeals Reports parallel alongside the North Western Reporter when available."),
        state("Minnesota", "mn", "Cite Minnesota cases primarily to the North Western Reporter (N.W.2d), using the shortened Court of Appeals abbreviation (Minn. App.) and the decision year in parentheses. Minn. R. App. P. 128.02 and 128.04 govern brief format and require an alphabetical table of authorities with page references. Cite statutes to Minnesota Statutes (Minn. Stat. § __)."),
        state("Mississippi", "ms", "Cite Mississippi cases to the Southern Reporter (So. 3d) with paragraph-number pinpoints assigned by the court. For decisions from July 1, 1997 forward, the clerk-assigned medium-neutral citation (e.g., 2023-SA-01079-SCT, ¶ 13) may be the primary cite or run in parallel with the reporter. Miss. R. App. P. 28 governs briefs and requires a table of contents and table of authorities with page references."),
        state("Missouri", "mo", "Cite Missouri cases primarily to the South Western Reporter (S.W.3d), with a Missouri Reports parallel when available. Supreme Court decisions heard en banc add \u{201C}banc\u{201D} after the jurisdiction (Mo. banc 2016); Court of Appeals citations indicate the district. Include page pinpoints. Mo. R. Civ. P. 84.04 and 84.16 govern brief citation."),
        state("Montana", "mt", "Montana requires a public-domain citation (e.g., 2025 MT 137) for cases decided from 1998 forward, with parallels to the Montana Reports and Pacific Reporter and paragraph-number pinpoints (¶ 21). Unpublished opinions from 1998 forward carry an \u{201C}N\u{201D} suffix (e.g., 1998 MT 1N) and may not be cited as precedent (Montana Supreme Court Order of Dec. 16, 1997)."),
        state("Nebraska", "ne", "Cite Nebraska cases to the Nebraska Reports / Nebraska Appellate Reports when available (now published electronically in the Nebraska Appellate Courts Online Library), and citations may include hyperlinks to the official reports (Neb. Ct. R. App. P. § 2-109). Court of Appeals decisions designated \u{201C}For Permanent Publication\u{201D} are binding precedent. Out-of-state cases cite the National Reporter System, else the official state report."),
        state("Nevada", "nv", "Cite Nevada cases to the Nevada Reports in parallel with the Pacific Reporter when available. For unpublished dispositions from Jan. 1, 2016 onward, cite an electronic database (if available) or give the docket number and filing date noted as an unpublished disposition. Nev. R. App. P. 28 and 36 govern briefs; unpublished dispositions are not mandatory precedent except in successive stages of the same or a related case."),
        state("New Hampshire", "nh", "Cite New Hampshire cases to the New Hampshire Reports when available; for decisions from 2024 forward a medium-neutral citation (e.g., 2025 NH 37, ¶ 10) is an alternative, using year-NH-sequential number with paragraph pinpoints (N.H. Sup. Ct. R. 20(5)). Always include the decision year in parentheses and page references to the cited material."),
        state("New Jersey", "nj", "Cite New Jersey cases to the official New Jersey Reports by volume; if not officially reported, say so and use the National Reporter System or other available source (N.J. Ct. R. 2:6-2). The New Jersey Manual on Style for Judicial Opinions gives detailed format. Unpublished opinions are not precedent and may be cited only for res judicata, collateral estoppel, or law-of-the-case purposes (R. 1:36-3)."),
        state("New Mexico", "nm", "Cite New Mexico appellate opinions using the official medium-neutral format (e.g., 2025-NMSC-009, ¶ 12) with paragraph pinpoints; the New Mexico Reports parallel is mandatory and the Pacific Reporter discretionary (N.M. Sup. Ct. R. 23-112). Cite statutes to NMSA 1978 with the year of enactment or latest amendment; follow Bluebook style for other authorities."),
        state("New York", "ny", "Cite New York appellate opinions with the official reporter first (N.Y.3d, A.D.3d, Misc. 3d), followed by the N.E.3d and N.Y.S.3d parallels (N.Y. Ct. App. R. 500.1(g)). Follow the New York Law Reporting Bureau's Official Reports Style Manual (the Tanbook) for detailed conventions."),
        state("North Carolina", "nc", "Cite North Carolina appellate opinions to the North Carolina Reports with the South Eastern Reporter parallel (e.g., 356 N.C. 40, 565 S.E.2d 172). Per N.C. R. App. P. 30, citing unpublished Court of Appeals decisions is disfavored except to establish claim preclusion or law of the case; if cited, note the unpublished status and serve copies. Follow Bluebook conventions with the regional-reporter parallel."),
        state("North Dakota", "nd", "For North Dakota Supreme Court opinions issued after Jan. 1, 1997, use the medium-neutral format with paragraph pinpoints (e.g., 1997 ND 15, ¶ 21), providing the North Western Reporter as a parallel when available; pre-1997 opinions cite N.W.2d with the state reporter. Per N.D. R. Ct. 11.6, the ¶ symbol is essential to distinguish paragraph numbers from page numbers."),
        state("Ohio", "oh", "Cite Ohio Supreme Court opinions with the medium-neutral format (e.g., 2024-Ohio-5685) followed by the official Ohio St. 3d reporter and the N.E.3d parallel; all opinions use numbered paragraphs for pinpoints. Consult the Ohio Supreme Court's Writing Manual: A Guide to Citations, Style, and Opinion Writing (Ohio Sup. Ct. R. 2.6)."),
        state("Oklahoma", "ok", "Cite Oklahoma Supreme Court opinions using the official medium-neutral paragraph format (e.g., 1995 OK 11, ¶ 9) with a mandatory Pacific Reporter parallel (e.g., 890 P.2d 922); published Court of Civil Appeals opinions also use the paragraph form (Okla. Sup. Ct. R. 1.200(f)). Unpublished opinions may not be cited in appellate briefs unless part of the trial record or cited as grounds for certiorari."),
        state("Oregon", "or", "Cite Oregon opinions to the state reporter (e.g., 334 Or. 587) with the Pacific Reporter parallel (54 P.3d 610); follow the Oregon Appellate Courts Style Manual. Cases affirmed without opinion by the Court of Appeals should not be cited as authority; set out relevant statutory or regulatory text verbatim with proper citation (Or. R. App. P. 5.30)."),
        state("Pennsylvania", "pa", "Cite Pennsylvania appellate opinions to the official Pennsylvania State Reports first (Pa.) with the Atlantic Reporter parallel (A.3d), and Superior/Commonwealth Court reports as applicable. For uncodified statutes, reference the Laws of Pennsylvania (Pamphlet Laws) (Pa. R. App. P. 2119(b)). State the principle for which a case is cited and give the pages quotations are taken from."),
        state("Rhode Island", "ri", "Cite Rhode Island Supreme Court opinions to the Atlantic Reporter (e.g., 893 A.2d 239 (R.I. 2006)) as the primary cite. Unpublished orders may not be cited and have no precedential effect (R.I. Sup. Ct. R. 16(j)). Briefs must include an alphabetical index of authorities with page references."),
        state("South Carolina", "sc", "Cite South Carolina appellate opinions to the South Carolina Reports first (S.C.) with the South Eastern Reporter parallel (e.g., 349 S.C. 613, 564 S.E.2d 653). Cite statutes to S.C. Code Ann. § __ (year) and regulations to the S.C. Code of Regulations (S.C. R. App. Prac. 268). Follow The Bluebook or the South Carolina research/citation guide for other authorities."),
        state("South Dakota", "sd", "Cite South Dakota Supreme Court opinions from Jan. 1, 1996 onward using the medium-neutral format with paragraph pinpoints (e.g., 2025 S.D. 53, ¶ 5) per SDCL § 15-26A-69.1, including the North Western Reporter cite when available; pre-1996 opinions cite the South Dakota Reports or N.W.2d by volume and page."),
        state("Tennessee", "tn", "Cite Tennessee opinions to the South Western Reporter as the primary reporter, always including the decision year (Tenn. R. App. P. 27), with pinpoints to the pertinent pages. Cite statutes to Tennessee Code Annotated (official edition). Opinions designated \u{201C}Not for Citation\u{201D} may not be used except for res judicata, collateral estoppel, or law of the case."),
        state("Texas", "tx", "Cite Texas opinions to the South Western Reporter (Tex. R. App. P. 38) and include the case's writ/petition history. Several Texas appellate courts require the Texas Rules of Form (the Greenbook, published by the Texas Law Review). Briefs must include an alphabetical index of authorities with page references."),
        state("Utah", "ut", "Cite Utah Supreme Court and Court of Appeals opinions issued on or after Jan. 1, 1999 using the medium-neutral format with paragraph pinpoints (e.g., 2015 UT 99, ¶ 3; 2015 UT App 320, ¶ 6) per Utah R. App. P. 24(f); earlier opinions cite the reporter by volume and page. This format is required in all documents filed with the courts."),
        state("Vermont", "vt", "Cite Vermont Supreme Court opinions issued on or after Jan. 1, 2003 using the medium-neutral format with paragraph pinpoints (e.g., 2001 VT 1, ¶ 12) per Vt. R. App. P. 28.2, followed by parallels to the Vermont Reports and Atlantic Reporter (e.g., 169 Vt. 203, 850 A.2d 421); earlier opinions cite by reporter volume and page."),
        state("Virginia", "va", "Cite Virginia opinions to the Virginia Reports with the South Eastern Reporter (Va. Sup. Ct. R. 5:27), always including the decision year. Unpublished opinions may be cited only as informative (not binding); if not in a public database, file a copy with the brief. Briefs must include an alphabetical table of authorities."),
        state("Washington", "wa", "Cite Washington opinions to the Washington Reports and Pacific Reporter, conforming to the Office of Reporter of Decisions style sheet (Wash. Gen. R. 14(d)), which incorporates The Bluebook with local abbreviations. Paragraph numbers may be used for pinpoints. Unpublished Court of Appeals opinions cannot be cited as authority."),
        state("West Virginia", "wv", "Cite West Virginia opinions to the West Virginia Reports and South Eastern Reporter, citing holdings to syllabus points in the prescribed form. Memorandum decisions may be cited if clearly denoted as such (e.g., Smith v. Jones, No. 11-098 (W. Va. Jan. 15, 2011) (memorandum decision)) per W. Va. R. App. P. 21."),
        state("Wisconsin", "wi", "Cite Wisconsin opinions issued on or after Jan. 1, 2000 using the public-domain medium-neutral format with paragraph pinpoints (e.g., 2000 WI 14, ¶ 6) per SCR ch. 80, followed by the Wisconsin Reports and North Western Reporter (SCR 80.02); earlier opinions use page-number pinpoints."),
        state("Wyoming", "wy", "Cite Wyoming Supreme Court opinions issued on or after Jan. 1, 2001 using the medium-neutral public-domain format with paragraph pinpoints (e.g., 2022 WY 66, ¶ 10) per the Wyoming Supreme Court's neutral-citation order. Opinions not to be cited as precedent carry an \u{201C}N\u{201D} suffix (e.g., 2001 WY 1N); withdrawn/vacated use \u{201C}W\u{201D} and amended use \u{201C}A\u{201D}.")
    ]

    public static let all: [CitationStyle] = general + states

    /// Looks up a style by its stored display name (the value persisted in the
    /// Assistant Profile), so saved selections resolve to their guidance.
    public static func style(named name: String) -> CitationStyle? {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        return all.first { $0.displayName == trimmed }
    }

    private static func state(_ name: String, _ abbreviation: String, _ guidance: String) -> CitationStyle {
        CitationStyle(id: "state-\(abbreviation)", displayName: name, guidance: guidance)
    }
}
