import SupraCore
import SupraSessions
import SwiftUI

/// Plans a research session: collects the issue + filters, generates exactly
/// five editable CourtListener queries with the local model (no network), and
/// saves the approved ones (spec §9 / WO 24).
struct ResearchPlannerView: View {
    @ObservedObject var controller: ResearchSessionController
    let matter: MatterSummary
    let loadedModelID: ModelID?

    @Environment(\.dismiss) private var dismiss
    @State private var draft: ResearchPlanDraft
    @State private var preferredCourtsText = ""
    @State private var excludedCourtsText = ""
    @State private var useDateRange = false
    @State private var startDate = Date(timeIntervalSince1970: 1_420_070_400) // 2015-01-01
    @State private var endDate = Date()

    init(controller: ResearchSessionController, matter: MatterSummary, loadedModelID: ModelID?) {
        self.controller = controller
        self.matter = matter
        self.loadedModelID = loadedModelID
        _draft = State(initialValue: ResearchPlanDraft(
            jurisdiction: matter.jurisdiction,
            partyPerspective: matter.partyPerspective.rawValue
        ))
    }

    var body: some View {
        VStack(spacing: 0) {
            Text("New Research Session")
                .font(.title2.weight(.semibold))
                .padding([.horizontal, .top])

            Form {
                Section("Issue") {
                    TextField("Title", text: $draft.title)
                        .accessibilityIdentifier("planner.title")
                    TextField("Legal issue or question", text: $draft.issueText, axis: .vertical)
                        .lineLimit(3...6)
                        .accessibilityIdentifier("planner.issue")
                    TextField("Jurisdiction", text: $draft.jurisdiction)
                        .accessibilityIdentifier("planner.jurisdiction")
                }

                Section("Filters (optional)") {
                    TextField("Preferred courts (comma-separated)", text: $preferredCourtsText)
                    TextField("Excluded courts (comma-separated)", text: $excludedCourtsText)
                    Toggle("Limit to a date range", isOn: $useDateRange)
                    if useDateRange {
                        DatePicker("From", selection: $startDate, displayedComponents: .date)
                        DatePicker("To", selection: $endDate, displayedComponents: .date)
                    }
                }

                Section {
                    Button { Task { await generate() } } label: {
                        HStack {
                            if isGenerating { ProgressView().controlSize(.small) }
                            Text(isGenerating ? "Generating…" : "Generate Search Plan")
                        }
                    }
                    .disabled(!draft.isValid || isGenerating)
                    .accessibilityIdentifier("planner.generate")
                    if let message = planMessage {
                        Text(message).font(.caption).foregroundStyle(.secondary)
                    }
                } footer: {
                    Text("Queries are generated by the local model. No network request is made until you run the plan.")
                }

                if showsQuerySection {
                    Section("Proposed Queries — approve the ones to run") {
                        ForEach($controller.plannedQueries) { $query in
                            HStack(spacing: 8) {
                                Toggle("Approved", isOn: $query.approved).labelsHidden()
                                    .accessibilityIdentifier("planner.approved")
                                TextField("Query", text: $query.text)
                                    .accessibilityIdentifier("planner.query")
                                Button(role: .destructive) {
                                    controller.deleteQuery(id: query.id)
                                } label: {
                                    Image(systemName: "trash")
                                }
                                .buttonStyle(.borderless)
                            }
                        }
                        Button { controller.addQuery() } label: {
                            Label("Add Query", systemImage: "plus")
                        }
                        .accessibilityIdentifier("planner.addQuery")
                    }
                }
            }
            .formStyle(.grouped)

            Divider()
            HStack {
                Button("Cancel", role: .cancel) {
                    controller.resetPlan()
                    dismiss()
                }
                Spacer()
                if !controller.plannedQueries.isEmpty {
                    Text("\(controller.approvedQueryCount) approved")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                Button("Save Plan") { save() }
                    .keyboardShortcut(.defaultAction)
                    .disabled(!controller.canSavePlan)
                    .accessibilityIdentifier("planner.save")
            }
            .padding()
        }
        .frame(width: 520, height: 660)
    }

    private var isGenerating: Bool {
        if case .generating = controller.planState { return true }
        return false
    }

    /// Show the query editor (incl. "Add Query") whenever there are queries OR a
    /// generation attempt has finished — so manual entry stays reachable when
    /// generation returns nothing (no model loaded / incomplete / failed).
    private var showsQuerySection: Bool {
        if !controller.plannedQueries.isEmpty { return true }
        switch controller.planState {
        case .ready, .incomplete, .failed: return true
        case .idle, .generating: return false
        }
    }

    private var planMessage: String? {
        switch controller.planState {
        case let .incomplete(message), let .failed(message):
            return message
        case .idle, .generating, .ready:
            return nil
        }
    }

    private func generate() async {
        syncFilters()
        await controller.generatePlan(draft: draft, modelID: loadedModelID)
    }

    private func save() {
        syncFilters()
        if (try? controller.savePlan(draft: draft)) != nil {
            dismiss()
        }
    }

    private func syncFilters() {
        draft.preferredCourts = splitList(preferredCourtsText)
        draft.excludedCourts = splitList(excludedCourtsText)
        draft.dateRangeStart = useDateRange ? startDate : nil
        draft.dateRangeEnd = useDateRange ? endDate : nil
    }

    private func splitList(_ text: String) -> [String] {
        text.split(separator: ",")
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
    }
}
